apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: basic-ubuntu
  namespace: vm-operator
spec:
  networkInterfaces:
  - networkName: "primary"
    networkType: vsphere-distributed
  className: best-effort-small
  imageName: ubuntu-20.04-vmservice-v1alpha1.20210210
  powerState: poweredOn
  storageClass: wcpglobal-storage-profile